/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as PlaylistImport } from './routes/playlist'
import { Route as MoviesImport } from './routes/movies'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as MoviesAlltotalImport } from './routes/movies/alltotal'
import { Route as MoviesWatchMovieImport } from './routes/movies/watch.$movie'
import { Route as MoviesGenreGenreIdImport } from './routes/movies/genre.$genreId'
import { Route as MoviesAllPageImport } from './routes/movies/all.$page'

// Create/Update Routes

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistRoute = PlaylistImport.update({
  path: '/playlist',
  getParentRoute: () => rootRoute,
} as any)

const MoviesRoute = MoviesImport.update({
  path: '/movies',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MoviesAlltotalRoute = MoviesAlltotalImport.update({
  path: '/alltotal',
  getParentRoute: () => MoviesRoute,
} as any)

const MoviesWatchMovieRoute = MoviesWatchMovieImport.update({
  path: '/watch/$movie',
  getParentRoute: () => MoviesRoute,
} as any)

const MoviesGenreGenreIdRoute = MoviesGenreGenreIdImport.update({
  path: '/genre/$genreId',
  getParentRoute: () => MoviesRoute,
} as any)

const MoviesAllPageRoute = MoviesAllPageImport.update({
  path: '/all/$page',
  getParentRoute: () => MoviesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesImport
      parentRoute: typeof rootRoute
    }
    '/playlist': {
      id: '/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof PlaylistImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/movies/alltotal': {
      id: '/movies/alltotal'
      path: '/alltotal'
      fullPath: '/movies/alltotal'
      preLoaderRoute: typeof MoviesAlltotalImport
      parentRoute: typeof MoviesImport
    }
    '/movies/all/$page': {
      id: '/movies/all/$page'
      path: '/all/$page'
      fullPath: '/movies/all/$page'
      preLoaderRoute: typeof MoviesAllPageImport
      parentRoute: typeof MoviesImport
    }
    '/movies/genre/$genreId': {
      id: '/movies/genre/$genreId'
      path: '/genre/$genreId'
      fullPath: '/movies/genre/$genreId'
      preLoaderRoute: typeof MoviesGenreGenreIdImport
      parentRoute: typeof MoviesImport
    }
    '/movies/watch/$movie': {
      id: '/movies/watch/$movie'
      path: '/watch/$movie'
      fullPath: '/movies/watch/$movie'
      preLoaderRoute: typeof MoviesWatchMovieImport
      parentRoute: typeof MoviesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  MoviesRoute: MoviesRoute.addChildren({
    MoviesAlltotalRoute,
    MoviesAllPageRoute,
    MoviesGenreGenreIdRoute,
    MoviesWatchMovieRoute,
  }),
  PlaylistRoute,
  SearchRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/movies",
        "/playlist",
        "/search"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/movies": {
      "filePath": "movies.tsx",
      "children": [
        "/movies/alltotal",
        "/movies/all/$page",
        "/movies/genre/$genreId",
        "/movies/watch/$movie"
      ]
    },
    "/playlist": {
      "filePath": "playlist.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/movies/alltotal": {
      "filePath": "movies/alltotal.tsx",
      "parent": "/movies"
    },
    "/movies/all/$page": {
      "filePath": "movies/all.$page.tsx",
      "parent": "/movies"
    },
    "/movies/genre/$genreId": {
      "filePath": "movies/genre.$genreId.tsx",
      "parent": "/movies"
    },
    "/movies/watch/$movie": {
      "filePath": "movies/watch.$movie.tsx",
      "parent": "/movies"
    }
  }
}
ROUTE_MANIFEST_END */
